# coding: utf-8

"""
    Firefly III API v2.1.0

    This is the documentation of the Firefly III API. You can find accompanying documentation on the website of Firefly III itself (see below). Please report any bugs or issues. You may use the \"Authorize\" button to try the API below. This file was last generated on 2024-09-10T05:07:57+00:00  Please keep in mind that the demo site does not accept requests from curl, colly, wget, etc. You must use a browser or a tool like Postman to make requests. Too many script kiddies out there, sorry about that. 

    The version of the OpenAPI document: 2.1.0
    Contact: james@firefly-iii.org
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from firefly_client.api.transactions_api import TransactionsApi


class TestTransactionsApi(unittest.TestCase):
    """TransactionsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = TransactionsApi()

    def tearDown(self) -> None:
        pass

    def test_delete_transaction(self) -> None:
        """Test case for delete_transaction

        Delete a transaction.
        """
        pass

    def test_delete_transaction_journal(self) -> None:
        """Test case for delete_transaction_journal

        Delete split from transaction
        """
        pass

    def test_get_transaction(self) -> None:
        """Test case for get_transaction

        Get a single transaction.
        """
        pass

    def test_get_transaction_by_journal(self) -> None:
        """Test case for get_transaction_by_journal

        Get a single transaction, based on one of the underlying transaction journals (transaction splits).
        """
        pass

    def test_list_attachment_by_transaction(self) -> None:
        """Test case for list_attachment_by_transaction

        Lists all attachments.
        """
        pass

    def test_list_event_by_transaction(self) -> None:
        """Test case for list_event_by_transaction

        Lists all piggy bank events.
        """
        pass

    def test_list_links_by_journal(self) -> None:
        """Test case for list_links_by_journal

        Lists all the transaction links for an individual journal (individual split).
        """
        pass

    def test_list_transaction(self) -> None:
        """Test case for list_transaction

        List all the user's transactions. 
        """
        pass

    def test_store_transaction(self) -> None:
        """Test case for store_transaction

        Store a new transaction
        """
        pass

    def test_update_transaction(self) -> None:
        """Test case for update_transaction

        Update existing transaction. For more information, see https://docs.firefly-iii.org/references/firefly-iii/api/specials/
        """
        pass


if __name__ == '__main__':
    unittest.main()
