# coding: utf-8

"""
    Firefly III API v2.1.0

    This is the documentation of the Firefly III API. You can find accompanying documentation on the website of Firefly III itself (see below). Please report any bugs or issues. You may use the \"Authorize\" button to try the API below. This file was last generated on 2024-09-10T05:07:57+00:00  Please keep in mind that the demo site does not accept requests from curl, colly, wget, etc. You must use a browser or a tool like Postman to make requests. Too many script kiddies out there, sorry about that. 

    The version of the OpenAPI document: 2.1.0
    Contact: james@firefly-iii.org
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from firefly_client.api.tags_api import TagsApi


class TestTagsApi(unittest.TestCase):
    """TagsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = TagsApi()

    def tearDown(self) -> None:
        pass

    def test_delete_tag(self) -> None:
        """Test case for delete_tag

        Delete an tag.
        """
        pass

    def test_get_tag(self) -> None:
        """Test case for get_tag

        Get a single tag.
        """
        pass

    def test_list_attachment_by_tag(self) -> None:
        """Test case for list_attachment_by_tag

        Lists all attachments.
        """
        pass

    def test_list_tag(self) -> None:
        """Test case for list_tag

        List all tags.
        """
        pass

    def test_list_transaction_by_tag(self) -> None:
        """Test case for list_transaction_by_tag

        List all transactions with this tag.
        """
        pass

    def test_store_tag(self) -> None:
        """Test case for store_tag

        Store a new tag
        """
        pass

    def test_update_tag(self) -> None:
        """Test case for update_tag

        Update existing tag.
        """
        pass


if __name__ == '__main__':
    unittest.main()
