# coding: utf-8

"""
    Firefly III API v2.1.0

    This is the documentation of the Firefly III API. You can find accompanying documentation on the website of Firefly III itself (see below). Please report any bugs or issues. You may use the \"Authorize\" button to try the API below. This file was last generated on 2024-09-10T05:07:57+00:00  Please keep in mind that the demo site does not accept requests from curl, colly, wget, etc. You must use a browser or a tool like Postman to make requests. Too many script kiddies out there, sorry about that. 

    The version of the OpenAPI document: 2.1.0
    Contact: james@firefly-iii.org
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from firefly_client.api.links_api import LinksApi


class TestLinksApi(unittest.TestCase):
    """LinksApi unit test stubs"""

    def setUp(self) -> None:
        self.api = LinksApi()

    def tearDown(self) -> None:
        pass

    def test_delete_link_type(self) -> None:
        """Test case for delete_link_type

        Permanently delete link type.
        """
        pass

    def test_delete_transaction_link(self) -> None:
        """Test case for delete_transaction_link

        Permanently delete link between transactions.
        """
        pass

    def test_get_link_type(self) -> None:
        """Test case for get_link_type

        Get single a link type.
        """
        pass

    def test_get_transaction_link(self) -> None:
        """Test case for get_transaction_link

        Get a single link.
        """
        pass

    def test_list_link_type(self) -> None:
        """Test case for list_link_type

        List all types of links.
        """
        pass

    def test_list_transaction_by_link_type(self) -> None:
        """Test case for list_transaction_by_link_type

        List all transactions under this link type.
        """
        pass

    def test_list_transaction_link(self) -> None:
        """Test case for list_transaction_link

        List all transaction links.
        """
        pass

    def test_store_link_type(self) -> None:
        """Test case for store_link_type

        Create a new link type
        """
        pass

    def test_store_transaction_link(self) -> None:
        """Test case for store_transaction_link

        Create a new link between transactions
        """
        pass

    def test_update_link_type(self) -> None:
        """Test case for update_link_type

        Update existing link type.
        """
        pass

    def test_update_transaction_link(self) -> None:
        """Test case for update_transaction_link

        Update an existing link between transactions.
        """
        pass


if __name__ == '__main__':
    unittest.main()
