# coding: utf-8

"""
    Firefly III API v2.1.0

    This is the documentation of the Firefly III API. You can find accompanying documentation on the website of Firefly III itself (see below). Please report any bugs or issues. You may use the \"Authorize\" button to try the API below. This file was last generated on 2024-09-10T05:07:57+00:00  Please keep in mind that the demo site does not accept requests from curl, colly, wget, etc. You must use a browser or a tool like Postman to make requests. Too many script kiddies out there, sorry about that. 

    The version of the OpenAPI document: 2.1.0
    Contact: james@firefly-iii.org
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from firefly_client.api.autocomplete_api import AutocompleteApi


class TestAutocompleteApi(unittest.TestCase):
    """AutocompleteApi unit test stubs"""

    def setUp(self) -> None:
        self.api = AutocompleteApi()

    def tearDown(self) -> None:
        pass

    def test_get_accounts_ac(self) -> None:
        """Test case for get_accounts_ac

        Returns all accounts of the user returned in a basic auto-complete array.
        """
        pass

    def test_get_bills_ac(self) -> None:
        """Test case for get_bills_ac

        Returns all bills of the user returned in a basic auto-complete array.
        """
        pass

    def test_get_budgets_ac(self) -> None:
        """Test case for get_budgets_ac

        Returns all budgets of the user returned in a basic auto-complete array.
        """
        pass

    def test_get_categories_ac(self) -> None:
        """Test case for get_categories_ac

        Returns all categories of the user returned in a basic auto-complete array.
        """
        pass

    def test_get_currencies_ac(self) -> None:
        """Test case for get_currencies_ac

        Returns all currencies of the user returned in a basic auto-complete array.
        """
        pass

    def test_get_currencies_code_ac(self) -> None:
        """Test case for get_currencies_code_ac

        Returns all currencies of the user returned in a basic auto-complete array. This endpoint is DEPRECATED and I suggest you DO NOT use it.
        """
        pass

    def test_get_object_groups_ac(self) -> None:
        """Test case for get_object_groups_ac

        Returns all object groups of the user returned in a basic auto-complete array.
        """
        pass

    def test_get_piggies_ac(self) -> None:
        """Test case for get_piggies_ac

        Returns all piggy banks of the user returned in a basic auto-complete array.
        """
        pass

    def test_get_piggies_balance_ac(self) -> None:
        """Test case for get_piggies_balance_ac

        Returns all piggy banks of the user returned in a basic auto-complete array complemented with balance information.
        """
        pass

    def test_get_recurring_ac(self) -> None:
        """Test case for get_recurring_ac

        Returns all recurring transactions of the user returned in a basic auto-complete array.
        """
        pass

    def test_get_rule_groups_ac(self) -> None:
        """Test case for get_rule_groups_ac

        Returns all rule groups of the user returned in a basic auto-complete array.
        """
        pass

    def test_get_rules_ac(self) -> None:
        """Test case for get_rules_ac

        Returns all rules of the user returned in a basic auto-complete array.
        """
        pass

    def test_get_tag_ac(self) -> None:
        """Test case for get_tag_ac

        Returns all tags of the user returned in a basic auto-complete array.
        """
        pass

    def test_get_transaction_types_ac(self) -> None:
        """Test case for get_transaction_types_ac

        Returns all transaction types returned in a basic auto-complete array. English only.
        """
        pass

    def test_get_transactions_ac(self) -> None:
        """Test case for get_transactions_ac

        Returns all transaction descriptions of the user returned in a basic auto-complete array.
        """
        pass

    def test_get_transactions_idac(self) -> None:
        """Test case for get_transactions_idac

        Returns all transactions, complemented with their ID, of the user returned in a basic auto-complete array. This endpoint is DEPRECATED and I suggest you DO NOT use it.
        """
        pass


if __name__ == '__main__':
    unittest.main()
