# coding: utf-8

"""
    Firefly III API v2.1.0

    This is the documentation of the Firefly III API. You can find accompanying documentation on the website of Firefly III itself (see below). Please report any bugs or issues. You may use the \"Authorize\" button to try the API below. This file was last generated on 2024-09-10T05:07:57+00:00  Please keep in mind that the demo site does not accept requests from curl, colly, wget, etc. You must use a browser or a tool like Postman to make requests. Too many script kiddies out there, sorry about that. 

    The version of the OpenAPI document: 2.1.0
    Contact: james@firefly-iii.org
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from firefly_client.models.piggy_bank import PiggyBank

class TestPiggyBank(unittest.TestCase):
    """PiggyBank unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PiggyBank:
        """Test PiggyBank
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PiggyBank`
        """
        model = PiggyBank()
        if include_optional:
            return PiggyBank(
                created_at = '2018-09-17T12:46:47+01:00',
                updated_at = '2018-09-17T12:46:47+01:00',
                account_id = '13',
                account_name = 'Savings account',
                name = 'New digital camera',
                currency_id = '5',
                currency_code = 'USD',
                currency_symbol = '$',
                currency_decimal_places = 2,
                target_amount = '123.45',
                percentage = 12.5,
                current_amount = '123.45',
                left_to_save = '700.00',
                save_per_month = '12.45',
                start_date = 'Mon Sep 17 00:00:00 UTC 2018',
                target_date = 'Mon Sep 17 00:00:00 UTC 2018',
                order = 5,
                active = True,
                notes = 'Some notes',
                object_group_id = '5',
                object_group_order = 5,
                object_group_title = 'Example Group'
            )
        else:
            return PiggyBank(
                account_id = '13',
                name = 'New digital camera',
                target_amount = '123.45',
        )
        """

    def testPiggyBank(self):
        """Test PiggyBank"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
