# coding: utf-8

"""
    Firefly III API v2.1.0

    This is the documentation of the Firefly III API. You can find accompanying documentation on the website of Firefly III itself (see below). Please report any bugs or issues. You may use the \"Authorize\" button to try the API below. This file was last generated on 2024-09-10T05:07:57+00:00  Please keep in mind that the demo site does not accept requests from curl, colly, wget, etc. You must use a browser or a tool like Postman to make requests. Too many script kiddies out there, sorry about that. 

    The version of the OpenAPI document: 2.1.0
    Contact: james@firefly-iii.org
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from firefly_client.api.bills_api import BillsApi


class TestBillsApi(unittest.TestCase):
    """BillsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = BillsApi()

    def tearDown(self) -> None:
        pass

    def test_delete_bill(self) -> None:
        """Test case for delete_bill

        Delete a bill.
        """
        pass

    def test_get_bill(self) -> None:
        """Test case for get_bill

        Get a single bill.
        """
        pass

    def test_list_attachment_by_bill(self) -> None:
        """Test case for list_attachment_by_bill

        List all attachments uploaded to the bill.
        """
        pass

    def test_list_bill(self) -> None:
        """Test case for list_bill

        List all bills.
        """
        pass

    def test_list_rule_by_bill(self) -> None:
        """Test case for list_rule_by_bill

        List all rules associated with the bill.
        """
        pass

    def test_list_transaction_by_bill(self) -> None:
        """Test case for list_transaction_by_bill

        List all transactions associated with the  bill.
        """
        pass

    def test_store_bill(self) -> None:
        """Test case for store_bill

        Store a new bill
        """
        pass

    def test_update_bill(self) -> None:
        """Test case for update_bill

        Update existing bill.
        """
        pass


if __name__ == '__main__':
    unittest.main()
