# coding: utf-8

"""
    Firefly III API v2.1.0

    This is the documentation of the Firefly III API. You can find accompanying documentation on the website of Firefly III itself (see below). Please report any bugs or issues. You may use the \"Authorize\" button to try the API below. This file was last generated on 2024-09-10T05:07:57+00:00  Please keep in mind that the demo site does not accept requests from curl, colly, wget, etc. You must use a browser or a tool like Postman to make requests. Too many script kiddies out there, sorry about that. 

    The version of the OpenAPI document: 2.1.0
    Contact: james@firefly-iii.org
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class ConfigValueUpdateFilter(str, Enum):
    """
    ConfigValueUpdateFilter
    """

    """
    allowed enum values
    """
    CONFIGURATION_DOT_IS_DEMO_SITE = 'configuration.is_demo_site'
    CONFIGURATION_DOT_PERMISSION_UPDATE_CHECK = 'configuration.permission_update_check'
    CONFIGURATION_DOT_LAST_UPDATE_CHECK = 'configuration.last_update_check'
    CONFIGURATION_DOT_SINGLE_USER_MODE = 'configuration.single_user_mode'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of ConfigValueUpdateFilter from a JSON string"""
        return cls(json.loads(json_str))


